spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student-manager
    username: root
    password: 130902
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
